//! Generates `$OUT_DIR/asset_manifest.rs` (see `src/asset_manifest.rs` for
//! why): embedded map JSON plus sprite/tileset name lists, discovered from
//! the asset directories at compile time so the wasm build needs no
//! filesystem and native needs no runtime read_dir.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

const MAPS_DIR: &str = "assets/data/maps";
const CHARACTERS_DIR: &str = "assets/textures/characters";
const TILESETS_DIR: &str = "assets/textures/tilesets";

/// Sorted file stems with the given extension. Sorted so the generated code
/// (and thus the binary) is deterministic regardless of directory order.
fn stems(dir: &Path, ext: &str) -> Vec<String> {
    let mut out: Vec<String> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("{} should exist: {e}", dir.display()))
        .flatten()
        .filter_map(|entry| {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some(ext) {
                return None;
            }
            path.file_stem()
                .and_then(|s| s.to_str())
                .map(str::to_string)
        })
        .collect();
    out.sort();
    out
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");

    let mut code = String::from(
        "// @generated by build.rs - do not edit, do not commit.\n\n",
    );

    // Maps: (name, embedded JSON). include_str! is anchored to
    // CARGO_MANIFEST_DIR with forward slashes (valid on Windows too), and it
    // makes rustc track each JSON file's content, so editing a map re-embeds
    // it even when build.rs itself doesn't re-run.
    code.push_str("pub static MAPS: &[(&str, &str)] = &[\n");
    for name in stems(&Path::new(&manifest_dir).join(MAPS_DIR), "json") {
        writeln!(
            code,
            "    ({name:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{MAPS_DIR}/{name}.json\"))),"
        )
        .unwrap();
    }
    code.push_str("];\n\n");

    for (const_name, dir) in [
        ("CHARACTER_SPRITES", CHARACTERS_DIR),
        ("TILESETS", TILESETS_DIR),
    ] {
        writeln!(code, "pub static {const_name}: &[&str] = &[").unwrap();
        for name in stems(&Path::new(&manifest_dir).join(dir), "png") {
            writeln!(code, "    {name:?},").unwrap();
        }
        code.push_str("];\n\n");
    }

    fs::write(Path::new(&out_dir).join("asset_manifest.rs"), code)
        .expect("write asset_manifest.rs");

    // Directory mtime changes on file add/remove/rename, which is exactly
    // the discovery case; content edits are covered by include_str! above.
    println!("cargo::rerun-if-changed={MAPS_DIR}");
    println!("cargo::rerun-if-changed={CHARACTERS_DIR}");
    println!("cargo::rerun-if-changed={TILESETS_DIR}");
}
