//! Compile-time manifest of shipped assets, generated by `build.rs` into
//! `$OUT_DIR/asset_manifest.rs`.
//!
//! The browser (wasm) build has no filesystem: `fs::read_dir` discovery and
//! `fs::read_to_string` map loading both fail there, and the failure mode is
//! the game hanging in `GameState::Loading` forever. Instead, `build.rs`
//! scans the asset directories at compile time and embeds map JSON
//! (`include_str!`) plus sprite/tileset name lists. Native builds use the
//! same manifest so there is exactly one code path; the tests below keep the
//! manifest honest against the real directories. "Drop a file in, it works"
//! survives because build.rs re-runs when the asset directories change.
//!
//! PNGs themselves are NOT embedded - only their names. Pixel data still
//! loads through the `AssetServer` (HTTP fetch on wasm, disk read natively).

include!(concat!(env!("OUT_DIR"), "/asset_manifest.rs"));

/// Embedded JSON for a map by name (file stem), or None if no such map
/// shipped in the binary.
pub fn map_json(name: &str) -> Option<&'static str> {
    MAPS.iter().find(|(n, _)| *n == name).map(|(_, json)| *json)
}

/// Names (file stems) of every shipped map.
pub fn map_names() -> impl Iterator<Item = &'static str> {
    MAPS.iter().map(|(name, _)| *name)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;
    use std::fs;

    /// File stems with the given extension actually present on disk.
    fn disk_stems(dir: &str, ext: &str) -> BTreeSet<String> {
        fs::read_dir(dir)
            .unwrap_or_else(|e| panic!("{dir} should exist: {e}"))
            .flatten()
            .filter_map(|entry| {
                let path = entry.path();
                if path.extension().and_then(|e| e.to_str()) != Some(ext) {
                    return None;
                }
                path.file_stem()
                    .and_then(|s| s.to_str())
                    .map(str::to_string)
            })
            .collect()
    }

    /// The embedded manifest must list exactly the maps shipped on disk -
    /// a map added to assets/data/maps must appear after a rebuild, and a
    /// deleted one must vanish (stale embedding would ship ghost content).
    #[test]
    fn manifest_map_names_match_disk() {
        let manifest: BTreeSet<String> = map_names().map(str::to_string).collect();
        assert_eq!(manifest, disk_stems("assets/data/maps", "json"));
    }

    /// Same honesty check for the sprite/tileset discovery lists that
    /// replaced the runtime fs::read_dir scan.
    #[test]
    fn manifest_character_and_tileset_stems_match_disk() {
        let characters: BTreeSet<String> =
            CHARACTER_SPRITES.iter().map(|s| s.to_string()).collect();
        assert_eq!(
            characters,
            disk_stems("assets/textures/characters", "png"),
            "character sprite manifest drifted from assets/textures/characters"
        );

        let tilesets: BTreeSet<String> = TILESETS.iter().map(|s| s.to_string()).collect();
        assert_eq!(
            tilesets,
            disk_stems("assets/textures/tilesets", "png"),
            "tileset manifest drifted from assets/textures/tilesets"
        );
    }

    /// Every embedded map must parse - a merge that breaks a map's JSON
    /// should fail here, not at scene-transition time in a release build.
    #[test]
    fn every_manifest_map_parses() {
        for name in map_names() {
            crate::map_data::MapData::load(name)
                .unwrap_or_else(|e| panic!("embedded map {name} failed to load: {e:#}"));
        }
    }
}
